src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\ActualityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="posts")
     *
     */
    private $user_id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="name")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", cascade={"persist", "remove"}, mappedBy="posts")
     */
    private $tags;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="post_id")
     */
    private $comments;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createDate;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LikeDislike", mappedBy="post_id")
     */
    private $likeDislikes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Actuality", mappedBy="post_id")
     */
    private $actualities;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Satisfied", mappedBy="post_id")
     */
    private $satisfieds;

    public function __toString()
    {
        return $this->title;
    }

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->createDate = new \DateTime();
        $this->likeDislikes = new ArrayCollection();
        $this->actualities = new ArrayCollection();
        $this->satisfieds = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
            $tag->addPost($this);
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
            $tag->removePost($this);
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPostId($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getPostId() === $this) {
                $comment->setPostId(null);
            }
        }

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getCreateDate(): ?\DateTimeInterface
    {
        return $this->createDate;
    }

    public function setCreateDate(\DateTimeInterface $createDate): self
    {
        $this->createDate = $createDate;

        return $this;
    }

    /**
     * @return Collection|LikeDislike[]
     */
    public function getLikeDislikes(): Collection
    {
        return $this->likeDislikes;
    }

    public function addLikeDislike(LikeDislike $likeDislike): self
    {
        if (!$this->likeDislikes->contains($likeDislike)) {
            $this->likeDislikes[] = $likeDislike;
            $likeDislike->setPostId($this);
        }

        return $this;
    }

    public function removeLikeDislike(LikeDislike $likeDislike): self
    {
        if ($this->likeDislikes->contains($likeDislike)) {
            $this->likeDislikes->removeElement($likeDislike);
            // set the owning side to null (unless already changed)
            if ($likeDislike->getPostId() === $this) {
                $likeDislike->setPostId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Actuality[]
     */
    public function getActualities(): Collection
    {
        return $this->actualities;
    }

    public function addActuality(Actuality $actuality): self
    {
        if (!$this->actualities->contains($actuality)) {
            $this->actualities[] = $actuality;
            $actuality->setPostId($this);
        }

        return $this;
    }

    public function removeActuality(Actuality $actuality): self
    {
        if ($this->actualities->contains($actuality)) {
            $this->actualities->removeElement($actuality);
            // set the owning side to null (unless already changed)
            if ($actuality->getPostId() === $this) {
                $actuality->setPostId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Satisfied[]
     */
    public function getSatisfieds(): Collection
    {
        return $this->satisfieds;
    }

    public function addSatisfied(Satisfied $satisfied): self
    {
        if (!$this->satisfieds->contains($satisfied)) {
            $this->satisfieds[] = $satisfied;
            $satisfied->setPostId($this);
        }

        return $this;
    }

    public function removeSatisfied(Satisfied $satisfied): self
    {
        if ($this->satisfieds->contains($satisfied)) {
            $this->satisfieds->removeElement($satisfied);
            // set the owning side to null (unless already changed)
            if ($satisfied->getPostId() === $this) {
                $satisfied->setPostId(null);
            }
        }

        return $this;
    }


}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}interactive{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ asset('vendor/font-awesome/css/fontawesome-all.min.css') }}">
        <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="navbarNav">
        <a class="navbar-brand" href="">
            {% if is_granted("ROLE_USER") %}
                {{ app.user.username }}
            {% endif %}
        </a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" id="app_homepage" href="{{ path('homepage') }}">Главная</a>
            </li>
            {% if is_granted("ROLE_USER") %}
                <li class="nav-item">
                    <a class="nav-link" id="app_profile" href="{{ path('profile') }}">Профиль</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="app_profile" href="{{ path('newPost') }}">Создать статью</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="app_logout" href="{{ path('fos_user_security_logout') }}">Выйти</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" id="app_register" href="{{ path('fos_user_registration_register') }}">Регистрация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="app_login" href="{{ path('fos_user_security_login') }}">Войти</a>
                </li>
            {% endif %}
            {% if categories is defined %}
                {% for category in categories %}
                    <li class="nav-item" style="color: #FFFFFF"><a class="nav-link" style="color: #FFFFFF; font-size: 16px; font-weight: bold;" href="{{ path('category_posts', {'id': category.id}) }}">{{ category.name }}</a></li>
                {% endfor %}
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container pt-4">
    <div class="row">
        <div class="col mx-auto">
            {% set notices = app.flashes('warning') %}
            {% set errors = app.flashes('error') %}

            {% if notices %}
                {% for message in notices %}
                    <div class="notice">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}

            {% if errors %}

                {% for message in errors %}
                    <div class="error">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col">
            {% block content %}{% endblock %}
        </div>
    </div>

</div>

{% block javascripts %}
    <script src="{{ asset('vendor/jquery/jquery-3.3.1.min.js') }}"></script>
    <script src="{{ asset('vendor/popper/js/popper.min.js') }}"></script>
    <script src="{{ asset('vendor/bootstrap/js/bootstrap.min.js') }}"></script>
{% endblock %}
</body>
</html>

templates/category.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3">
            <ul>
                {% for tag in tags %}
                    <li><a href="{{ path('tag_posts', {'id': tag.id}) }}">{{ tag.name }}</a></li>
                {% endfor %}

            </ul>
        </div>
        <div class="col-9">
            {% for post in posts  %}
                {% if post.date is not null and post.date <= date() %}
                    <h3><a href="{{ path('one_post', {'id': post.id}) }}">{{ post.title }}</a></h3>
                    <p>{{ post.description }}</p>
                {% endif %}
            {% endfor %}
        </div>

    </div>

{% endblock %}

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}

{% block content %}
<div class="row">
    <div class="col-3">
        <ul>
            {% for tag in tags %}
                <li><a href="{{ path('tag_posts', {'id': tag.id}) }}">{{ tag.name }}</a></li>
            {% endfor %}

        </ul>
    </div>
    <div class="col-9">
        {% for post in pages  %}
            {% if post.date is not null and post.date <= date() %}
                <h3><a href="{{ path('one_post', {'id': post.id}) }}">{{ post.title }}</a></h3>
                <p>{{ post.description }}</p>
            {% endif %}
        {% endfor %}
        <div class="navigation">
            {{ knp_pagination_render(pages) }}
        </div>
    </div>




</div>

{% endblock %}

templates/newPost.html.twig
{% extends 'base.html.twig' %}

{% block content %}
<h2>Создать новость</h2>

    {{ form(form) }}
{% endblock %}

{% block title %}

{% endblock %}

templates/post.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}

{% block content %}
    <h3><a href="">{{ post.title }}</a></h3>
    <p>Дата создания:{{ post.createDate | date('Y-m-d') }} - Дата публикации {{ post.date | date('Y-m-d') }} </p>
    <p>автор:{{ post.userId.username }}</p>
    <p>{{ post.description }}</p>
    <div class="btn-group mr-2" role="group" aria-label="First group">
        <a class="btn btn-secondary" href="{{ path('markPost', {'post': post.id,'type': 'l', 'mark': 1}) }}">качественно</a>
        <a class="btn btn-secondary" href="{{ path('markPost', {'post': post.id,'type': 'l', 'mark': -1}) }}">не качественно</a>
        <a class="btn btn-outline-success" >{{ like }}</a>
    </div>

    <div class="btn-group mr-2" role="group" aria-label="Second group">
        <a class="btn btn-secondary" href="{{ path('markPost', {'post': post.id,'type': 's', 'mark': 1}) }}">доволен</a>
        <a class="btn btn-secondary" href="{{ path('markPost', {'post': post.id,'type': 's', 'mark': -1}) }}">не доволен</a>
        <a class="btn btn-outline-success" >{{ happy }}</a>
    </div>

    <div class="btn-group mr-2" role="group" aria-label="First group">
        <a class="btn btn-secondary" href="{{ path('markPost', {'post': post.id,'type': 'a', 'mark': 1}) }}">актуально</a>
        <a class="btn btn-secondary" href="{{ path('markPost', {'post': post.id,'type': 'a', 'mark': -1}) }}">не актуально</a>
        <a class="btn btn-outline-success" >{{ actuality }}</a>
    </div>

    <hr>

    <h2>Комментарии</h2>
    <hr>
    {{ form(form) }}
    <div>
        {% for comment in comments  %}
            <div>
                <h4>{{ comment.userId.email }}</h4>
                <p>{{ comment.message }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/profile.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <h1>Профиль</h1>
<h2>{{ user.email }}</h2>
    <hr>
    <h2>Рейтинг</h2>
    <h3>{{ rating }}</h3>
{% endblock %}

{% block title %}

{% endblock %}